packages:
  - packages/*

catalog:
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.7.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.0.4
  '@vitest/coverage-v8': ^3.2.4
  jsdom: ^27.0.0
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  typescript-eslint: ^8.46.1
  vite: ^7.1.9
  vitest: ^3.2.4

onlyBuiltDependencies:
  - deasync
  - dprint
  - esbuild
  - unrs-resolver

minimumReleaseAge: 1440 # 1 day
