packages:
  - packages/*

catalog:
  '@eslint/js': 9.39.2
  '@storybook/addon-a11y': 10.1.10
  '@storybook/addon-docs': 10.1.10
  '@storybook/addon-vitest': 10.1.10
  '@storybook/react-vite': 10.1.10
  '@tanstack/react-query': 5.90.12
  '@tanstack/react-router': 1.143.11
  '@tanstack/react-router-devtools': 1.143.11
  '@tanstack/router-core': 1.143.6
  '@tanstack/router-plugin': 1.143.11
  '@testing-library/dom': 10.4.1
  '@testing-library/react': 16.3.1
  '@types/node': 24.10.4
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.2
  '@vitest/browser-playwright': 4.0.16
  '@vitest/coverage-v8': 4.0.16
  classnames: 2.5.1
  dprint: 0.50.2
  eslint: 9.39.2
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-pnpm: 1.4.3
  eslint-plugin-postcss-modules: 2.0.0
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.26
  eslint-plugin-storybook: 10.1.10
  globals: 16.5.0
  husky: 9.1.7
  jsdom: 27.4.0
  jsonc-eslint-parser: 2.4.2
  playwright: 1.57.0
  react: 19.2.3
  react-dom: 19.2.3
  storybook: 10.1.10
  turbo: 2.7.2
  typescript: 5.9.3
  typescript-eslint: 8.50.1
  vite: 7.3.0
  vitest: 4.0.16
  yaml-eslint-parser: 1.3.2

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - deasync
  - dprint
  - esbuild
  - unrs-resolver
