packages:
  - packages/*

catalog:
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.10.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/coverage-v8': ^4.0.15
  jsdom: ^27.2.0
  react: ^19.2.1
  react-dom: ^19.2.1
  typescript: ^5.9.3
  typescript-eslint: ^8.46.3
  vite: ^7.2.4
  vitest: ^4.0.15

onlyBuiltDependencies:
  - deasync
  - dprint
  - esbuild
  - unrs-resolver

minimumReleaseAge: 1440 # 1 day
