packages:
  - packages/*

catalog:
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.4.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.2
  '@vitest/coverage-v8': ^3.2.4
  jsdom: ^26.1.0
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.2
  typescript-eslint: ^8.43.0
  vite: ^7.1.5
  vitest: ^3.2.4

onlyBuiltDependencies:
  - deasync
  - dprint
  - esbuild
  - unrs-resolver
