packages:
  - packages/*

catalog:
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.3.0
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react': ^5.0.1
  jsdom: ^26.1.0
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.2
  typescript-eslint: ^8.40.0
  vite: ^7.1.2
  vitest: ^3.2.4

onlyBuiltDependencies:
  - deasync
  - dprint
  - esbuild
  - unrs-resolver
