DO $$ BEGIN
    DROP TABLE IF EXISTS ygo_cards;

    DROP TYPE IF EXISTS YGO_CARD_KIND;
    DROP TYPE IF EXISTS YGO_MONSTER_KIND;
    DROP TYPE IF EXISTS YGO_MONSTER_SUBTYPE;
    DROP TYPE IF EXISTS YGO_MONSTER_ATTRIBUTE;
    DROP TYPE IF EXISTS YGO_MONSTER_RACE;
    DROP TYPE IF EXISTS YGO_SPELL_KIND;
    DROP TYPE IF EXISTS YGO_TRAP_KIND;
END $$;
