name: "cardfolio"

services:
  cardfolio:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: cardfolio
    environment:
      PGHOST: db
      PGUSER: cardfolio
      PGPASSWORD: cardfolio
      CARDFOLIO_DB: postgres://cardfolio:cardfolio@db/cardfolio
      CARDFOLIO_DB_TEST: postgres://cardfolio:cardfolio@db/cardfolio_test
      CARDFOLIO_LOGLEVEL: DEBUG
    volumes:
      - ..:/workspace

  db:
    image: postgres:18
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: cardfolio
      POSTGRES_PASSWORD: cardfolio
      POSTGRES_DB: cardfolio
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/setup_test_db.sh:/docker-entrypoint-initdb.d/setup_test_db.sh

volumes:
  db-data:
