[package]
name = "cardfolio-backend"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "cardfolio"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["multipart"] }
bitflags = "2.9.1"
chrono = { version = "0.4.41", features = ["serde"] }
rust_decimal = { version = "1.37.2", features = ["db-postgres"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["compression-gzip", "fs", "limit", "trace"] }
tower_governor = "0.7.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
http-body-util = "0.1.3"
temp-env = "0.3.6"
tower = "0.5.2"
