[package]
name = "cardfolio-backend"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "cardfolio"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.99"
axum = { version = "0.8.4", features = ["multipart"] }
base64 = "0.22.1"
bb8 = "0.9.0"
bb8-postgres = "0.9.0"
bitflags = "2.9.4"
chrono = { version = "0.4.42", features = ["serde"] }
form_urlencoded = "1.2.2"
futures-util = "0.3.31"
postgres-types = { version = "0.2.9", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["http2", "charset", "rustls-tls"], default-features = false }
serde = { version = "1.0.221", features = ["derive"] }
serde_html_form = "0.2.8"
serde_json = "1.0.145"
serde_path_to_error = "0.1.17"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["compression-gzip", "fs", "limit", "trace", "normalize-path"] }
tower_governor = "0.8.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[dev-dependencies]
http-body-util = "0.1.3"
rand = "0.9.2"
temp-env = "0.3.6"
